from scipy.spatial import ConvexHull
from distance3d import colliders, gjk
import itertools
import numpy as np
from Naive import Naive

def chToPointsHelper(ch, allPts):
    chPts = []
    for s in ch.simplices:
        for i in s:
            chPts.append(allPts[i])
    return chPts

def pointInside(ch1, ch2):
    naive = Naive(None)
    for p in ch1:
        for t in itertools.combinations(ch2, 4):
            # if any of ch1's points are inside ch2 return true
            if (naive.inTetrahedron(t, p)):
                return True
    for p in ch2:
        for t in itertools.combinations(ch1, 4):
            # if any of ch2's points are inside ch1 return true
            if (naive.inTetrahedron(t, p)):
                return True
    return False


# https://alexanderfabisch.github.io/distance3d/_auto_examples/gjk/plot_convex_mesh.html#sphx-glr-auto-examples-gjk-plot-convex-mesh-py
def gjkDetectCollision(ch1, ch2):
    # convert ch vertices to colliders
    collider_a = colliders.ConvexHullVertices(ch1)
    collider_b = colliders.ConvexHullVertices(ch2)
    dist, p1, p2, _ = gjk.gjk(collider_a, collider_b)
    return dist == 0

            

# tests generated by claude
def main():
# Test 1: Clear intersection - one tetrahedron inside the other
    print("Test 1: One tetrahedron fully inside another")
    points1 = np.array([(0,0,0), (4,0,0), (0,4,0), (0,0,4)], dtype=float)
    points2 = np.array([(1,1,0), (2,1,0), (1,2,0), (1,1,1)], dtype=float)    # small, inside
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    verts1 = points1[ch1.vertices]
    verts2 = points2[ch2.vertices]

    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    result2 = gjkDetectCollision(verts1, verts2)
    print(f"Expected: True  | Got: {result} and {result2}")

    # Test 2: Clearly separated, no intersection
    print("\nTest 2: Completely separate tetrahedra")
    points1 = np.array([(0,0,0), (1,0,0), (0,1,0), (0,0,1)], dtype=float)
    points2 = np.array([(5,5,5), (6,5,5), (5,6,5), (5,5,6)], dtype=float)
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    verts1 = points1[ch1.vertices]
    verts2 = points2[ch2.vertices]
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    result2 = gjkDetectCollision(verts1, verts2)
    print(f"Expected: False | Got: {result} and {result2}")

    # Test 3: Partial overlap - vertex of ch2 pokes into ch1
    print("\nTest 3: One vertex of ch2 inside ch1")
    points1 = np.array([(0,0,0), (4,0,0), (0,4,0), (0,0,4)], dtype=float)
    points2 = np.array([(1,1,1), (6,0,0), (0,6,0), (0,0,6)], dtype=float)   # only (1,1,1) is inside ch1
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    verts1 = points1[ch1.vertices]
    verts2 = points2[ch2.vertices]
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    result2 = gjkDetectCollision(verts1, verts2)
    print(f"Expected: True  | Got: {result} and {result2}")

    # Test 4: Sharing a face but no vertex inside the other
    print("\nTest 4: Touching at a face, no vertex inside")
    points1 = np.array([(0,0,0), (2,0,0), (0,2,0), (0,0,2)], dtype=float)
    points2 = np.array([(2,0,0), (0,2,0), (0,0,2), (2,2,2)], dtype=float)   # shares a face with ch1
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    verts1 = points1[ch1.vertices]
    verts2 = points2[ch2.vertices]
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    result2 = gjkDetectCollision(verts1, verts2)
    print(f"Expected: True | Got: {result} and {result2}")
    
if __name__ == "__main__":
    main()