from scipy.spatial import HalfspaceIntersection, ConvexHull
import itertools
import numpy as np
from Naive import Naive

def chToPointsHelper(ch, allPts):
    chPts = []
    for s in ch.simplices:
        for i in s:
            chPts.append(allPts[i])
    return chPts

def pointInside(ch1, ch2):
    naive = Naive(None)
    for p in ch1:
        for t in itertools.combinations(ch2, 4):
            # if any of ch1's points are inside ch2 return true
            if (naive.inTetrahedron(t, p)):
                return True
    for p in ch2:
        for t in itertools.combinations(ch1, 4):
            # if any of ch2's points are inside ch1 return true
            if (naive.inTetrahedron(t, p)):
                return True
    return False
            

# tests generated by claude
def main():
# Test 1: Clear intersection - one tetrahedron inside the other
    print("Test 1: One tetrahedron fully inside another")
    points1 = [(0,0,0), (4,0,0), (0,4,0), (0,0,4)]   # big
    points2 = [(1,1,0), (2,1,0), (1,2,0), (1,1,1)]    # small, inside
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    print(f"Expected: True  | Got: {result}")

    # Test 2: Clearly separated, no intersection
    print("\nTest 2: Completely separate tetrahedra")
    points1 = [(0,0,0), (1,0,0), (0,1,0), (0,0,1)]
    points2 = [(5,5,5), (6,5,5), (5,6,5), (5,5,6)]
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    print(f"Expected: False | Got: {result}")

    # Test 3: Partial overlap - vertex of ch2 pokes into ch1
    print("\nTest 3: One vertex of ch2 inside ch1")
    points1 = [(0,0,0), (4,0,0), (0,4,0), (0,0,4)]
    points2 = [(1,1,1), (6,0,0), (0,6,0), (0,0,6)]   # only (1,1,1) is inside ch1
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    print(f"Expected: True  | Got: {result}")

    # Test 4: Sharing a face but no vertex inside the other
    print("\nTest 4: Touching at a face, no vertex inside")
    points1 = [(0,0,0), (2,0,0), (0,2,0), (0,0,2)]
    points2 = [(2,0,0), (0,2,0), (0,0,2), (2,2,2)]   # shares a face with ch1
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    print(f"Expected: False | Got: {result}")

    # Test 5: Identical hulls
    print("\nTest 5: Identical tetrahedra")
    points1 = [(0,0,0), (2,0,0), (0,2,0), (0,0,2)]
    points2 = [(0,0,0), (2,0,0), (0,2,0), (0,0,2)]
    ch1 = ConvexHull(points1)
    ch2 = ConvexHull(points2)
    result = pointInside(chToPointsHelper(ch1, points1), chToPointsHelper(ch2, points2))
    print(f"Expected: True  | Got: {result}")
if __name__ == "__main__":
    main()