import numpy as np
import itertools
from scipy.spatial import Delaunay

def findOrientation(p1, p2, p3, p4):
    matrix = np.array([[p1[0], p1[1], p1[2], 1],
                       [p2[0], p2[1], p2[2], 1],
                       [p3[0], p3[1], p3[2], 1],
                       [p4[0], p4[1], p4[2], 1]])
    volume = np.linalg.det(matrix) / 6
    if abs(volume) < 1e-9:
        return 0
    elif volume > 0: 
        return 1
    else: 
        return -1

def inTetrahedron(t, p):
    # find orientation of tetrahedron faces
    a = findOrientation(t[0], t[1], t[2], t[3])
    b = findOrientation(t[0], t[2], t[3], t[1])
    c = findOrientation(t[1], t[0], t[3], t[2])
    d = findOrientation(t[2], t[1], t[3], t[0])

    # find volumes of tetrahedrons made with faces to tested point
    a1 = findOrientation(t[0], t[1], t[2], p)
    b1 = findOrientation(t[0], t[2], t[3], p)
    c1 = findOrientation(t[1], t[0], t[3], p)
    d1 = findOrientation(t[2], t[1], t[3], p)

    # if p is coplanar with any face its not inside
    if a == 0 or a1 == 0 or b == 0 or b1 == 0 or c == 0 or c1 == 0 or d == 0 or d1 == 0:
        return False

    if a == a1 and b == b1 and c == c1 and d == d1:
        return True
    else:
        return False
    
def findExtremePts(pts):
    nonExtreme = []
    for p in pts:
        for t in itertools.combinations(pts, 4):
            if inTetrahedron(t, p):
                nonExtreme.append(p)
    return [p for p in pts if p not in nonExtreme]


# p1, p2, and p3 is a face on the polygon
# def isExtremeFace(p1, p2, p3, pts):
#     firstOrientation = None
#     for p in pts:
#         # don't compare p with itself
#         if p1 == p or p2 == p or p3 == p:
#             continue

#         o = findOrientation(p1, p2, p3, p)

#         # if point is coplanar continue cause that's fine
#         if o == 0:
#             continue
#         # if we don't have the first orientation, set it
#         if firstOrientation is None:
#             firstOrientation = o
#         # if one point is on the other side, its not an extreme face
#         elif o != firstOrientation:
#             return False
#     return True

# def findExtremeFaces(pts):
#     # for each possible triangle
#     extremeFaces = []
#     for t in itertools.combinations(pts, 3):
#         p1, p2, p3 = t
#         # if every pt is on the same side as t its an extreme face
#         if isExtremeFace(p1, p2, p3, pts):
#             extremeFaces.append(t)
#     return extremeFaces


# tests generated by copilot
def main():
    print("Test 1: ")
    tetrahedron = [
        (0, 0, 0),
        (1, 0, 0),
        (0, 1, 0),
        (0.5, 0.5, 0.5),
        (1, 1, 1),
        (0, 0, 1)
    ]
    hull = np.array(findExtremePts(tetrahedron))
    print(hull)
    tri = Delaunay(hull)
    print(f"  Input: {len(tetrahedron)} points")
    print(f"  Extreme pts: {len(hull)}")
    for f in tri.simplices:
        print(f"    {f}")

    # Test 2: Cube (8 points)
    print("\nTest 2: Cube")
    cube = [
        (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
        (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1), (0, 0, 0)
    ]
    hull = findExtremePts(cube)
    print(f"  Input: {len(cube)} points")
    print(f"  Extreme pts: {len(hull)}")
    for f in hull:
        print(f"    {f}")

    # Test 3: Pyramid (5 points)
    print("\nTest 3: Square Pyramid")
    pyramid = [
        (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),  # base
        (0.5, 0.5, 1)  # apex
    ]
    hull = findExtremePts(pyramid)
    print(f"  Input: {len(pyramid)} points")
    print(f"  Extreme pts: {len(hull)}")
    for f in hull:
        print(f"    {f}")

if __name__ == "__main__":
    main()