import numpy as np
import itertools

def findOrientation(p1, p2, p3, p4):
    # Use homogeneous coordinates to compute signed volume of tetrahedron
    matrix = np.array([[p1[0], p1[1], p1[2], 1],
                       [p2[0], p2[1], p2[2], 1],
                       [p3[0], p3[1], p3[2], 1],
                       [p4[0], p4[1], p4[2], 1]])
    return np.linalg.det(matrix) / 6

# def inTetrahedron(t, p):
#     # find orientation of tetrahedron faces
#     a = findOrientation(t[0], t[1], t[2], t[3])
#     b = findOrientation(t[0], t[2], t[3], t[1])
#     c = findOrientation(t[1], t[0], t[3], t[2])
#     d = findOrientation(t[2], t[1], t[3], t[0])

#     # find volumes of tetrahedrons made with faces to tested point
#     a1 = findOrientation(t[0], t[1], t[2], p)
#     b1 = findOrientation(t[0], t[2], t[3], p)
#     c1 = findOrientation(t[1], t[0], t[3], p)
#     d1 = findOrientation(t[2], t[1], t[3], p)

#     if a == a1 and b == b1 and c == c1 and d == d1:
#         return True
#     else:
#         return False
    
# pts should not include p1, p2, and p3
# p1, p2, and p3 is a face on the polygon
def isExtremeFace(p1, p2, p3, pts):
    firstOrientation = findOrientation(p1, p2, p3, pts[0])
    for i in range(1, len(pts)):
        if findOrientation(p1, p2, p3, pts[i]) != firstOrientation:
            return False
    return True

def findExtremeFaces(pts):
    # for each possible triangle
    extremeFaces = []
    for t in itertools.combinations(pts, 3):
        remaining = [p for p in pts if p not in t]
        # if every pt is on the same side as t its an extreme face
        if isExtremeFace(t[0], t[1], t[2], remaining):
            extremeFaces.append(t)
    return extremeFaces


# tests generated by copilot
def main():
    # Test 1: Tetrahedron (4 points)
    print("Test 1: Tetrahedron")
    tetrahedron = [
        (0, 0, 0),
        (1, 0, 0),
        (0, 1, 0),
        (0, 0, 1)
    ]
    faces = findExtremeFaces(tetrahedron)
    print(f"  Input: {len(tetrahedron)} points")
    print(f"  Extreme faces: {len(faces)}")
    for f in faces:
        print(f"    {f}")

    # Test 2: Cube (8 points)
    print("\nTest 2: Cube")
    cube = [
        (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
        (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)
    ]
    faces = findExtremeFaces(cube)
    print(f"  Input: {len(cube)} points")
    print(f"  Extreme faces: {len(faces)}")
    for f in faces:
        print(f"    {f}")

    # Test 3: Pyramid (5 points)
    print("\nTest 3: Square Pyramid")
    pyramid = [
        (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),  # base
        (0.5, 0.5, 1)  # apex
    ]
    faces = findExtremeFaces(pyramid)
    print(f"  Input: {len(pyramid)} points")
    print(f"  Extreme faces: {len(faces)}")
    for f in faces:
        print(f"    {f}")

if __name__ == "__main__":
    main()