import numpy as np
import itertools
from scipy.spatial import Delaunay, ConvexHull


# class containing naive implementations of calculating a convex hull and finding intersections
# of two convex hulls
class Naive:

    # constructor
    def __init__(self, pts):
        self.pts = pts

    # find and return volume of a given tetrahedron
    def findOrientation(self, p1, p2, p3, p4):
        matrix = np.array([[p1[0], p1[1], p1[2], 1],
                        [p2[0], p2[1], p2[2], 1],
                        [p3[0], p3[1], p3[2], 1],
                        [p4[0], p4[1], p4[2], 1]])
        volume = np.linalg.det(matrix) / 6
        # if the volume is close enough to zero its coplanar
        if abs(volume) < 1e-9:
            return 0
        elif volume > 0: 
            return 1
        else: 
            return -1

    
    def inTetrahedron(self, t, p):
        # find orientation of tetrahedron faces
        a = self.findOrientation(t[0], t[1], t[2], t[3])
        b = self.findOrientation(t[0], t[2], t[3], t[1])
        c = self.findOrientation(t[1], t[0], t[3], t[2])
        d = self.findOrientation(t[2], t[1], t[3], t[0])

        # find volumes of tetrahedrons made with faces to tested point
        a1 = self.findOrientation(t[0], t[1], t[2], p)
        b1 = self.findOrientation(t[0], t[2], t[3], p)
        c1 = self.findOrientation(t[1], t[0], t[3], p)
        d1 = self.findOrientation(t[2], t[1], t[3], p)

        # if p is coplanar with any face its not inside
        if a == 0 or a1 == 0 or b == 0 or b1 == 0 or c == 0 or c1 == 0 or d == 0 or d1 == 0:
            return False

        if a == a1 and b == b1 and c == c1 and d == d1:
            return True
        else:
            return False

    # p1, p2, and p3 is a face on the polygon
    def isExtremeFace(self, p1, p2, p3):
        firstOrientation = None
        for p in self.pts:
            # make sure we're not using a duplicate point
            if p1 == p or p2 == p or p3 == p:
                continue

            o = self.findOrientation(p1, p2, p3, p)

            # if point is coplanar continue cause that's fine
            if o == 0:
                continue
            # if we don't have the first orientation, set it
            if firstOrientation is None:
                firstOrientation = o
            # if one point is on the other side, its not an extreme face
            elif o != firstOrientation:
                return False
        return True

    # input should be a triangulated polygon and its faces should not be coplanar
    def findExtremeFaces(self):
        # for each possible triangle
        extremeFaces = []
        for t in itertools.combinations(self.pts, 3):
            p1, p2, p3 = t
            # if every pt is on the same side as t its an extreme face
            if self.isExtremeFace(p1, p2, p3):
                extremeFaces.append(t)
        return self.removeCoplanarFaces(extremeFaces)

    # CLEANING TO REMOVE REDUNDANT COPLANAR TRIANGLES (GENERATED BY CHATGPT)
    def samePlane(self, face1, face2):
        """
        Returns True if two triangles are coplanar
        """

        a, b, c = face1
        d, e, f = face2

        if self.findOrientation(a, b, c, d) != 0:
            return False
        if self.findOrientation(a, b, c, e) != 0:
            return False
        if self.findOrientation(a, b, c, f) != 0:
            return False

        return True

    def removeCoplanarFaces(self, faces):
        """
        Groups coplanar triangles together and removes redundant ones.

        Returns a cleaner triangulation.
        """

        planeGroups = []

        # Step 1: group coplanar faces
        for face in faces:
            placed = False

            for group in planeGroups:
                if self.samePlane(face, group[0]):
                    group.append(face)
                    placed = True
                    break

            if not placed:
                planeGroups.append([face])

        cleanedFaces = []

        # Step 2: reduce each coplanar group
        for group in planeGroups:

            # already unique
            if len(group) == 1:
                cleanedFaces.append(group[0])
                continue

            # collect unique vertices
            vertices = list(set(v for face in group for v in face))

            # if only 3 points, keep triangle
            if len(vertices) == 3:
                cleanedFaces.append(tuple(vertices))
                continue

            # use scipy 2d ConvexHull on coplanar points
            # project by dropping the dominant normal axis

            pts = np.array(vertices)

            # estimate normal from first triangle
            p0, p1, p2 = np.array(group[0])
            normal = np.cross(p1 - p0, p2 - p0)
            normal = np.abs(normal)

            # find which axis to "drop" so we can convert to a 2d polygon
            drop_axis = np.argmax(normal)

            projected = np.delete(pts, drop_axis, axis=1)

            # find 2d convex hull and then triangulate that
            hull2d = ConvexHull(projected)

            boundary = [vertices[i] for i in hull2d.vertices]

            # triangulate fan from first point
            for i in range(1, len(boundary) - 1):
                cleanedFaces.append((
                    boundary[0],
                    boundary[i],
                    boundary[i + 1]
                ))

        return cleanedFaces

    def pointInside(self, ch1, ch2):
        for p in ch1:
            for t in itertools.combinations(ch2, 4):
                # if any of ch1's points are inside ch2 return true
                if (self.inTetrahedron(t, p)):
                    return True
        for p in ch2:
            for t in itertools.combinations(ch1, 4):
                # if any of ch2's points are inside ch1 return true
                if (self.inTetrahedron(t, p)):
                    return True
        return False



def main():
    testConvexHull()
    testPointInside()

# tests generated by claude
def testConvexHull():
    print("TESTING NAIVE CONVEX HULL")

    def runTest(name, points, expectedFaceCount, expectedVertices):
        n = Naive(points)
        output = n.findExtremeFaces()
        actualVertices = set(v for face in output for v in face)
        expectedVertexSet = set(expectedVertices)

        facePass = len(output) == expectedFaceCount
        vertPass = actualVertices == expectedVertexSet
        passed = facePass and vertPass

        print(f"\n  {name}: {'PASS' if passed else 'FAIL'}")
        print(f"    Faces:    got {len(output)}, expected {expectedFaceCount} {'✓' if facePass else '✗'}")
        print(f"    Vertices: got {len(actualVertices)}, expected {len(expectedVertexSet)} {'✓' if vertPass else '✗'}")
        if not passed:
            print(f"    Face list:")
            for face in output:
                print(f"      {face}")
            if not vertPass:
                extra = actualVertices - expectedVertexSet
                missing = expectedVertexSet - actualVertices
                if extra:
                    print(f"    Unexpected vertices: {sorted(extra)}")
                if missing:
                    print(f"    Missing vertices:    {sorted(missing)}")

    runTest(
        "Tetrahedron",
        points=[(0,0,0),(1,0,0),(0,1,0),(0,0,1)],
        expectedFaceCount=4,
        expectedVertices=[(0,0,0),(1,0,0),(0,1,0),(0,0,1)]
    )
    runTest(
        "Triangular prism",
        points=[(0,0,0),(2,0,0),(1,2,0),(0,0,1),(2,0,1),(1,2,1)],
        expectedFaceCount=8,
        expectedVertices=[(0,0,0),(2,0,0),(1,2,0),(0,0,1),(2,0,1),(1,2,1)]
    )
    runTest(
        "Cube",
        points=[(0,0,0),(1,0,0),(1,1,0),(0,1,0),(0,0,1),(1,0,1),(1,1,1),(0,1,1)],
        expectedFaceCount=12,
        expectedVertices=[(0,0,0),(1,0,0),(1,1,0),(0,1,0),(0,0,1),(1,0,1),(1,1,1),(0,1,1)]
    )
    runTest(
        "Pyramid",
        points=[(0,0,0),(2,0,0),(2,2,0),(0,2,0),(1,1,2)],
        expectedFaceCount=6,
        expectedVertices=[(0,0,0),(2,0,0),(2,2,0),(0,2,0),(1,1,2)]
    )
    runTest(
        "Pyramid with interior point (interior point should be excluded)",
        points=[(0,0,0),(2,0,0),(2,2,0),(0,2,0),(1,1,2),(1,1,0.5)],
        expectedFaceCount=6,
        expectedVertices=[(0,0,0),(2,0,0),(2,2,0),(0,2,0),(1,1,2)]
    )
    runTest(
        "Random convex polyhedron",
        points=[(0,0,0),(2,0,0),(0,2,0),(0,0,2),(2,2,2),(1,3,1),(3,1,1)],
        expectedFaceCount=10,
        expectedVertices=[(0,0,0),(2,0,0),(0,2,0),(0,0,2),(2,2,2),(1,3,1),(3,1,1)]
    )
    runTest(
        "Cube with interior point (interior point should be excluded)",
        points=[(0,0,0),(2,0,0),(2,2,0),(0,2,0),(0,0,2),(2,0,2),(2,2,2),(0,2,2),(1,1,1)],
        expectedFaceCount=12,
        expectedVertices=[(0,0,0),(2,0,0),(2,2,0),(0,2,0),(0,0,2),(2,0,2),(2,2,2),(0,2,2)]
    )
    runTest(
        "Degenerate 2D square",
        points=[(0,0,0),(1,0,0),(1,1,0),(0,1,0)],
        expectedFaceCount=2,
        expectedVertices=[(0,0,0),(1,0,0),(1,1,0),(0,1,0)]
    )


def testPointInside():
    print("\nTESTING NAIVE CONVEX HULL INTERSECTION")

    def runTest(name, pts1, pts2, expected):
        n1 = Naive(pts1)
        n2 = Naive(pts2)
        hull1 = list(set(v for face in n1.findExtremeFaces() for v in face))
        hull2 = list(set(v for face in n2.findExtremeFaces() for v in face))
        result = n1.pointInside(hull1, hull2)
        passed = result == expected
        print(f"\n  {name}: {'PASS' if passed else 'FAIL'}")
        print(f"    Got {result}, expected {expected} {'✓' if passed else '✗'}")

    cube1 = [(0,0,0),(1,0,0),(1,1,0),(0,1,0),(0,0,1),(1,0,1),(1,1,1),(0,1,1)]
    cube2 = [(5,5,5),(6,5,5),(6,6,5),(5,6,5),(5,5,6),(6,5,6),(6,6,6),(5,6,6)]
    big   = [(0,0,0),(4,0,0),(4,4,0),(0,4,0),(0,0,4),(4,0,4),(4,4,4),(0,4,4)]
    small = [(1,1,1),(2,1,1),(2,2,1),(1,2,1),(1,1,2),(2,1,2),(2,2,2),(1,2,2)]
    cubeA = [(0,0,0),(2,0,0),(2,2,0),(0,2,0),(0,0,2),(2,0,2),(2,2,2),(0,2,2)]
    cubeB = [(1,1,1),(3,1,1),(3,3,1),(1,3,1),(1,1,3),(3,1,3),(3,3,3),(1,3,3)]
    tet   = [(0,0,0),(3,0,0),(0,3,0),(0,0,3)]
    tetA  = [(0,0,0),(1,0,0),(0,1,0),(0,0,1)]
    tetB  = [(2,0,0),(3,0,0),(2,1,0),(2,0,1)]
    outer = [(0,0,0),(10,0,0),(0,10,0),(0,0,10)]
    inner = [(1,1,1),(2,1,1),(1,2,1),(1,1,2)]

    runTest("Separated cubes",                           cube1, cube2, expected=False)
    runTest("Small cube fully inside large cube",        big,   small, expected=True)
    runTest("Partially overlapping cubes",               cubeA, cubeB, expected=True)
    runTest("Tetrahedra sharing one vertex only",        tetA,  tetB,  expected=False)
    runTest("Identical tetrahedra (our naive will fail)",                      tet,   tet,   expected=True)
    runTest("Tetrahedra close but not touching",         tetA,  tetB,  expected=False)
    runTest("Partial overlap forwards",                  cubeA, cubeB, expected=True)
    runTest("Partial overlap reversed (symmetry check)", cubeB, cubeA, expected=True)
    runTest("Small tetrahedron inside large",            outer, inner, expected=True)

if __name__ == "__main__":
    main()